name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      #
      # -----------------------------
      # 1) Install & Start Supabase
      # -----------------------------
      #
      # Install Supabase CLI using GitHub Action
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Start Supabase Database for tests
      - name: Start Supabase Database
        run: supabase db start

      #
      # -----------------------------
      # 2) Set up Deno
      # -----------------------------
      #
      # Install Deno
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Check Deno version
      - name: Verify Deno Installation
        run: deno --version

      #
      # -------------------------------------------
      # 3) Run TypeScript checks, build, & tests
      # -------------------------------------------
      #
      - name: Run TypeScript checks
        run: npm run typecheck

      - name: Build project
        run: npm run build

      # Run tests using Makefile, which now includes Deno tests
      - name: Run all tests
        run: make test-ci

      #
      # -------------------------------------------
      # 4) Tear down Supabase
      # -------------------------------------------
      #
      - name: Stop Supabase
        if: always()
        run: supabase db stop
