name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      #
      # -----------------------------
      # 1) Install & Start Supabase
      # -----------------------------
      #
      - name: Install Supabase CLI
        run: |
          # Example using a direct download of the CLI. Adjust version as needed.
          wget -qO supabase.tar.gz https://github.com/supabase/cli/releases/download/v1.78.0/supabase_1.78.0_linux_amd64.tar.gz
          tar xzf supabase.tar.gz supabase
          sudo mv supabase /usr/local/bin/supabase
          supabase --version

      - name: Start Supabase
        run: supabase start &
        # This starts Postgres, GoTrue, etc. in Docker containers in the background.

      - name: Wait for Supabase
        run: |
          # Wait a bit for containers to finish initializing
          sleep 10

      #
      # -----------------------------
      # 2) Apply migrations & seeds
      # -----------------------------
      #
      - name: Migrate database
        run: supabase db push
        # This applies everything in supabase/migrations/* to the local DB.

      - name: Seed database with test data
        run: |
          # By default, local supabase runs Postgres on port 54322
          psql "postgres://postgres:postgres@localhost:54322/postgres" \
            -f ./supabase/tests/test_data.sql

      #
      # -------------------------------------------
      # 3) Run TypeScript checks, build, & tests
      # -------------------------------------------
      #
      - name: Run TypeScript checks
        run: npm run typecheck

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      #
      # -------------------------------------------
      # 4) (Optional) Tear down Supabase
      # -------------------------------------------
      #
      # Not strictly necessary if the job ends, but
      # you can explicitly stop the containers if you like.
      - name: Stop Supabase
        if: always()
        run: docker compose down
