name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      #
      # -----------------------------
      # 1) Install & Start Supabase
      # -----------------------------
      #
      - name: Install Supabase CLI
        run: |
          wget -qO supabase.tar.gz https://github.com/supabase/cli/releases/download/v2.1.1/supabase_linux_amd64.tar.gz
          rm -rf supabase
          tar xzf supabase.tar.gz supabase
          sudo mv supabase /usr/local/bin/supabase
          supabase --version

      - name: Start Docker service
        run: |
          sudo service docker start
          docker info

      - name: Start Supabase
        run: supabase start &
        # Starts Postgres, GoTrue, etc., in Docker containers in the background.

      - name: Wait for Supabase
        run: |
          timeout=60
          while ! nc -z localhost 54322; do
            timeout=$((timeout - 1))
            if [ $timeout -eq 0 ]; then
              echo "Supabase services failed to start in time."
              exit 1
            fi
            sleep 1
          done

      #
      # -----------------------------
      # 2) Apply migrations & seeds
      # -----------------------------
      #
      - name: Migrate database
        run: supabase --config ./supabase/config.toml db push

      - name: Seed database with test data
        run: |
          psql "postgres://postgres:postgres@localhost:54322/postgres" \
            -f ./supabase/tests/test_data.sql

      #
      # -------------------------------------------
      # 3) Run TypeScript checks, build, & tests
      # -------------------------------------------
      #
      - name: Run TypeScript checks
        run: npm run typecheck

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      #
      # -------------------------------------------
      # 4) Tear down Supabase
      # -------------------------------------------
      #
      - name: Stop Supabase
        if: always()
        run: docker compose down
