name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      #
      # -----------------------------
      # 1) Install & Start Supabase
      # -----------------------------
      #
      # Install Supabase CLI using GitHub Action
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Start Supabase Database for tests
      - name: Start Supabase Database
        run: supabase db start

      # Wait for Supabase to initialize
      - name: Wait for Supabase
        run: |
          timeout=60
          while ! nc -z localhost 54322; do
            timeout=$((timeout - 1))
            if [ $timeout -eq 0 ]; then
              echo "Supabase services failed to start in time."
              exit 1
            fi
            sleep 1
          done

      # Apply database migrations
      - name: Migrate database
        run: supabase --config ./supabase/config.toml db push

      # Seed the database with test data
      - name: Seed database with test data
        run: |
          psql "postgres://postgres:postgres@localhost:54322/postgres" \
            -f ./supabase/tests/test_data.sql

      #
      # -------------------------------------------
      # 2) Run TypeScript checks, build, & tests
      # -------------------------------------------
      #
      - name: Run TypeScript checks
        run: npm run typecheck

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      #
      # -------------------------------------------
      # 3) Tear down Supabase
      # -------------------------------------------
      #
      - name: Stop Supabase
        if: always()
        run: supabase db stop
